name: CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "master"
permissions:
  contents: read
  
      
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout respository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: first11
          # Container registry password
          password: u+BuOp49QAUyWmsTIo6Yy4BdKvtrq2HJyaPP3onAW6+ACRA1yaPq
          # Container registry server url
          login-server: first11.azurecr.io

      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: first11.azurecr.io/hello-world-app:${{github.sha}}
          file: ./Dockerfile


      
  deployToAKS:
    permissions:
      actions: read
      contents: read
      id-token: write
  
  
    runs-on: ubuntu-latest
    needs: [buildImage]
    environment: Production
    steps:
      - name: checkout respository code
        uses: actions/checkout@v3
        
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
         client-id: '2c8304fa-8b98-41fc-8af7-4e219bf6227d'
         tenant-id: '87237b00-021c-4fff-9d2e-0df0b5fae856'
         subscription-id: '27825376-be3a-4328-b6eb-b2fc74363e63'
         
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with: 
          kubelogin-version: 'v0.0.25'
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          # Acceptable values: generic or arc
          cluster-type:  arc
          # Acceptable values: kubeconfig or service-account or service-principal
          method: kubeconfig
          # Contents of kubeconfig file
          kubeconfig: # optional
          # If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen
          context: # optional
          # Cluster Url
          k8s-url: # optional
          # Service account secret (run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name)
          k8s-secret: # optional
          # Token extracted from the secret of service account (should be base 64 decoded)
          token: # optional
         
          # Azure resource group name
          resource-group: 'demo_group'
          # Azure connected cluster name
          cluster-name: 'first
          
          
          '
          subscription: '27825376-be3a-4328-b6eb-b2fc74363e63'
          admin: "false"
          use-kubelogin: "true"
      
      - name: Deploys app
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: 
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images:
            first11.azurecr.io/hello-world-app:${{github.sha}}
            
















